'use strict';

// MCM BFF — Expo Router server adapter for Docker/Node.js deployment.
// Built output (dist/) is generated by: nx export-server mcm-app
// See infrastructure-as-code/docker/bff/compose.yaml for runtime env vars.

const { createRequestHandler } = require('@expo/server/adapter/express');
const express = require('express');
const path = require('path');
const { pathToFileURL } = require('url');

// Feature 012: Metro rewrites `import.meta.url` in bundled deps to
// `globalThis.__ExpoImportMetaRegistry.url`. The Metro dev server populates that registry,
// but the exported `@expo/server` runtime does NOT — so any bundled dependency that runs
// `createRequire(import.meta.url)` (e.g. @copilotkit/runtime's lazily-required adapter on
// the /bff-api/agent/run path) crashes at request time with
// "TypeError: Cannot read properties of undefined (reading 'url')", and the request hangs.
// Metro uses a single shared registry whose `.url` is the same for every module, so a flat
// object pointing at this server module is faithful and lets createRequire resolve against
// the deployed node_modules. Must run BEFORE createRequestHandler loads the bundle.
if (!globalThis.__ExpoImportMetaRegistry) {
  globalThis.__ExpoImportMetaRegistry = { url: pathToFileURL(__filename).href };
}

const app = express();
const PORT = parseInt(process.env.PORT ?? '3000', 10);
const DIST_CLIENT = path.join(__dirname, 'dist', 'client');
const DIST_SERVER = path.join(__dirname, 'dist', 'server');

// Feature 007: emit a marker on every response so E2E can positively prove the request
// path is THIS container (BFF_SOURCE=dev-container|prod-container), not the Metro dev
// server (which never sets this header). Defeats a silent "Metro answered on the port"
// false-green. The value is set per compose service via the BFF_SOURCE env var.
const BFF_SOURCE = process.env.BFF_SOURCE ?? 'unknown';
app.use((_req, res, next) => {
  res.setHeader('X-BFF-Source', BFF_SOURCE);
  next();
});

// Serve pre-built static web assets with long cache headers
app.use(
  express.static(DIST_CLIENT, {
    maxAge: process.env.NODE_ENV === 'production' ? '1y' : '0',
    immutable: process.env.NODE_ENV === 'production',
  })
);

// Expo Router handles all remaining requests:
//   /bff-api/*  → API route handlers (BFF)
//   /*          → SSR pages (web frontend)
app.all('*', createRequestHandler({ build: DIST_SERVER, mode: process.env.NODE_ENV ?? 'production' }));

app.listen(PORT, '0.0.0.0', () => {
  console.log(`MCM BFF listening on port ${PORT}`);
});
