'use strict';

// MCM BFF — Expo Router server adapter for Docker/Node.js deployment.
// Built output (dist/) is generated by: nx export-server mcm-app
// See infrastructure-as-code/docker/bff/compose.yaml for runtime env vars.

const { createRequestHandler } = require('@expo/server/adapter/express');
const express = require('express');
const path = require('path');
const { pathToFileURL } = require('url');
const { buildWebSecurityHeaders, isApiPath } = require('./web-security-headers');

// Feature 012: Metro rewrites `import.meta.url` in bundled deps to
// `globalThis.__ExpoImportMetaRegistry.url`. The Metro dev server populates that registry,
// but the exported `@expo/server` runtime does NOT — so any bundled dependency that runs
// `createRequire(import.meta.url)` (e.g. @copilotkit/runtime's lazily-required adapter on
// the /bff-api/agent/run path) crashes at request time with
// "TypeError: Cannot read properties of undefined (reading 'url')", and the request hangs.
// Metro uses a single shared registry whose `.url` is the same for every module, so a flat
// object pointing at this server module is faithful and lets createRequire resolve against
// the deployed node_modules. Must run BEFORE createRequestHandler loads the bundle.
if (!globalThis.__ExpoImportMetaRegistry) {
  globalThis.__ExpoImportMetaRegistry = { url: pathToFileURL(__filename).href };
}

const app = express();
const PORT = parseInt(process.env.PORT ?? '3000', 10);
const DIST_CLIENT = path.join(__dirname, 'dist', 'client');
const DIST_SERVER = path.join(__dirname, 'dist', 'server');

// Feature 032 (US1, FR-004): drop the `X-Powered-By: Express` banner (server-technology
// disclosure, ZAP 10037) from every response.
app.disable('x-powered-by');

// Feature 032 (US1): global baseline security headers on every browser-rendered/static response
// (FR-001..FR-004, FR-010). The browser-facing Keycloak origin for the CSP `connect-src` is read
// from env once at boot (FR-007) — never hard-coded; precedence mirrors src/config/keycloak.ts
// (empty string treated as absent). The web CSP is precomputed here and stamped per request.
const KEYCLOAK_ORIGIN =
  process.env.EXPO_PUBLIC_KEYCLOAK_URL ||
  process.env.KEYCLOAK_PUBLIC_URL ||
  process.env.KEYCLOAK_URL ||
  'http://localhost:8099';
const WEB_SECURITY_HEADERS = buildWebSecurityHeaders({ keycloakOrigin: KEYCLOAK_ORIGIN });
const WEB_CSP = WEB_SECURITY_HEADERS['Content-Security-Policy'];

// Feature 007: emit a marker on every response so E2E can positively prove the request
// path is THIS container (BFF_SOURCE=dev-container|prod-container), not the Metro dev
// server (which never sets this header). Defeats a silent "Metro answered on the port"
// false-green. The value is set per compose service via the BFF_SOURCE env var.
const BFF_SOURCE = process.env.BFF_SOURCE ?? 'unknown';
app.use((_req, res, next) => {
  res.setHeader('X-BFF-Source', BFF_SOURCE);
  next();
});

// Feature 032 (US1): stamp the baseline security headers before static serving + the Expo
// adapter, so they reach static assets, SSR HTML, and the API surface alike (the same layer that
// already stamps X-BFF-Source — proven to reach all three response classes). The three static
// headers apply to ALL paths; the web-app CSP is PATH-SCOPED to non-`/bff-api` requests so the API
// keeps its strict `default-src 'none'` handler CSP as the only CSP present (FR-005/FR-006 — the
// deterministic alternative to relying on adapter same-name merge order; research R4).
app.use((req, res, next) => {
  res.setHeader('X-Frame-Options', WEB_SECURITY_HEADERS['X-Frame-Options']);
  res.setHeader('X-Content-Type-Options', WEB_SECURITY_HEADERS['X-Content-Type-Options']);
  res.setHeader('Referrer-Policy', WEB_SECURITY_HEADERS['Referrer-Policy']);
  if (!isApiPath(req.path)) {
    res.setHeader('Content-Security-Policy', WEB_CSP);
  }
  next();
});

// Serve pre-built static web assets with long cache headers
app.use(
  express.static(DIST_CLIENT, {
    maxAge: process.env.NODE_ENV === 'production' ? '1y' : '0',
    immutable: process.env.NODE_ENV === 'production',
  })
);

// Expo Router handles all remaining requests:
//   /bff-api/*  → API route handlers (BFF)
//   /*          → SSR pages (web frontend)
app.all('*', createRequestHandler({ build: DIST_SERVER, mode: process.env.NODE_ENV ?? 'production' }));

app.listen(PORT, '0.0.0.0', () => {
  console.log(`MCM BFF listening on port ${PORT}`);
});
