#!/usr/bin/env bash
# cd-deploy build-deploy — "Scan, push (by tag + digest), build manifest + promotion file".
#
# Extracted from the workflow so it runs through scripts/ci-log-step.sh (feature 042): the Trivy
# CRITICAL table + push output are mirrored to the failure-digest log dir and the failing-step marker
# is recorded. This is the exact step that blocked the deploy on the npm-bundled-tar CVE with a digest
# that could not name it. Body is verbatim from the prior inline step.
#
# Inherits env from the workflow step/job: REGISTRY, NS, REGISTRY_USER, REGISTRY_TOKEN, GITHUB_SHA,
# GITHUB_OUTPUT. Writes deploy-manifest.json / env-deploy.body / env-deploy.generated to the CWD and
# `manifest=` to $GITHUB_OUTPUT (the step keeps id: publish), exactly as before.
set -euo pipefail
: "${REGISTRY:?set REGISTRY var}" "${NS:?set NS var}" "${REGISTRY_USER:?set REGISTRY_USER var}"
echo "$REGISTRY_TOKEN" | docker login "$REGISTRY" -u "$REGISTRY_USER" --password-stdin
# local-tag : registry-repo  (per contracts/image-and-digest-promotion.md)
map="mc-service:latest=mc-service mcm-bff:latest=mcm-bff agent-gateway:latest=agent-gateway \
     movie-mcp:latest=movie-mcp web-api-mcp:latest=web-api-mcp spreadsheet-mcp:latest=spreadsheet-mcp"
entries=""
: > env-deploy.body
for pair in $map; do
  local_tag="${pair%%=*}"; repo="${pair##*=}"
  ref="${REGISTRY}/${NS}/${repo}:${GITHUB_SHA}"
  docker tag "$local_tag" "$ref"
  # Block only on ACTIONABLE criticals: --ignore-unfixed skips CVEs with no upstream fix
  # (e.g. agent-gateway's debian perl-base CVE-2026-42496/8376 are fix_deferred/affected with
  # no fixed version) so the deploy isn't dead-ended on things we can't patch. A CRITICAL that
  # HAS a fix still fails the job.
  echo "── Trivy scan $repo (block on fixable CRITICAL) ──"
  trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed --no-progress "$local_tag"
  docker push "$ref"
  digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$ref" | cut -d'@' -f2)
  pinned="${REGISTRY}/${NS}/${repo}@${digest}"
  echo "$repo -> $pinned"
  # Assemble the run manifest in pure shell (no jq/python dependency on the runner).
  # The manifest is a job-local artifact (never committed) so it may carry the full ref.
  entry="\"$repo\":{\"tag\":\"$ref\",\"digest\":\"$pinned\"}"
  entries="${entries:+$entries,}$entry"
  # Promotion file body: VAR=<BARE sha256 digest> — HOST-FREE (R10, T029). No registry host
  # in git: the compose assembles ${REGISTRY_HOST}/jumbleknot/<repo>@${<REPO>_DIGEST}, with
  # REGISTRY_HOST injected from the gitignored .env.prod (Komodo). $digest is already the bare
  # `sha256:…` (cut from RepoDigests above). var = <REPO_UPPER>_DIGEST (mcm-bff → MCM_BFF_DIGEST).
  varname="$(echo "$repo" | tr 'a-z-' 'A-Z_')_DIGEST"
  echo "${varname}=${digest}" >> env-deploy.body
done
manifest="{$entries}"
echo "$manifest" > deploy-manifest.json
echo "manifest=$manifest" >> "$GITHUB_OUTPUT"
# Final .env.deploy content (header + the VAR=<bare digest> lines). The deploy job drops this in.
{
  echo "# GENERATED by cd-deploy (${GITHUB_SHA}) — digest-by-git promotion. DO NOT EDIT BY HAND."
  echo "# Each VAR pins the immutable BARE sha256 digest CI built+scanned+pushed this run."
  echo "# HOST-FREE (R10): no registry host here — the compose assembles the full ref as"
  echo "#   image: \${REGISTRY_HOST}/jumbleknot/<svc>@\${<SVC>_DIGEST}"
  echo "# with REGISTRY_HOST from the gitignored .env.prod (Komodo Variable)."
  echo "# Komodo wiring: prod-mcm-bff Stack — Run Directory infrastructure-as-code/docker/bff,"
  echo "# Env File Path .env.prod (secrets + REGISTRY_HOST), Additional Env Files .env.deploy"
  echo "# (this file). Komodo runs: docker compose --env-file .env.prod --env-file .env.deploy up"
  echo "# so \${MCM_BFF_DIGEST} interpolates from HERE (git), REGISTRY_HOST + secrets from .env.prod."
  cat env-deploy.body
} > env-deploy.generated
echo "── generated .env.deploy (written to all prod stack dirs) ──"; cat env-deploy.generated
