// Item #218 — guards on the check that verifies the lockfile refresh fires UNAIDED.
//
// The check exists because item #184 spent a week waiting on a condition that had already been met,
// and then recorded a wrong conclusion from a dry run. A comment saying "look again on Friday" is
// the thing that failed; this is the check that replaces it.
//
// The load-bearing discrimination is UNAIDED vs AIDED. A lock-file PR proves nothing on its own —
// PR #199 existed and was produced by a human ticking `unlimit-branch` on the Dependency Dashboard.
// The mechanical tell is WHEN it was created: `update/branch/index.js:244` returns `not-scheduled`
// before branch creation, and only `dependencyDashboardCheck` bypasses it. So a PR created OUTSIDE
// the permitted window cannot have come from the schedule.
//
// Pure functions over fixtures — no network.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseWindow, inWindow, classify } from '../check-lockfile-refresh.mjs';

const CONFIG = { timezone: 'America/New_York', schedule: ['* 2-4 * * 5'], lockFileMaintenance: { schedule: ['* 2-4 * * 5'] } };

test('the window is derived from renovate.json, not restated', () => {
  const w = parseWindow(CONFIG);
  assert.equal(w.timezone, 'America/New_York');
  assert.deepEqual([...w.hours].sort((a, b) => a - b), [2, 3, 4]);
  assert.deepEqual([...w.dow], [5]);
});

test('parseWindow prefers lockFileMaintenance own schedule over the inherited one', () => {
  const w = parseWindow({ timezone: 'America/New_York', schedule: ['* 9 * * 1'], lockFileMaintenance: { schedule: ['* 2-4 * * 5'] } });
  assert.deepEqual([...w.hours].sort((a, b) => a - b), [2, 3, 4], 'the child schedule beats the top-level one, as Renovate resolves it');
});

test('inWindow follows the DECLARED timezone across both DST offsets', () => {
  const w = parseWindow(CONFIG);
  // 2026-08-21 is a Friday in EDT (UTC-4): 07:00Z = 03:00 EDT — inside 02:00-04:59.
  assert.equal(inWindow('2026-08-21T07:00:14Z', w), true, 'the Friday 07:00Z cron is inside the window under EDT');
  // 2026-08-15T03:14:38Z is 2026-08-14 23:14 EDT — a Friday, but 23:14, not 02:00-04:59.
  assert.equal(inWindow('2026-08-15T03:14:38Z', w), false, "PR #199's real timestamp must read as OUTSIDE the window");
  // In January the offset is EST (UTC-5), so 07:00Z = 02:00 EST — still inside.
  assert.equal(inWindow('2027-01-15T07:00:00Z', w), true, 'the same cron is inside the window under EST too');
  // ...but 06:00Z in January is 01:00 EST — outside.
  assert.equal(inWindow('2027-01-15T06:00:00Z', w), false, 'an hour that is only inside under EDT must not read as inside under EST');
});

const window_ = parseWindow(CONFIG);
const MEND = 'This PR has been generated by [Mend Renovate CLI](https://github.com/renovatebot/renovate).';

test('no branch and no PR is STILL_STARVED', () => {
  const r = classify({ branches: ['main', 'renovate/cargo-deps'], pulls: [], window: window_, since: '2026-08-22T00:00:00Z' });
  assert.equal(r.verdict, 'STILL_STARVED');
  assert.equal(r.pr, null);
});

test('a lock-file PR created INSIDE the window is UNAIDED', () => {
  const pulls = [{ number: 300, created_at: '2026-08-28T07:04:00Z', title: 'chore(deps): lock file maintenance', body: MEND, head: { ref: 'renovate/lock-file-maintenance' } }];
  const r = classify({ branches: ['renovate/lock-file-maintenance'], pulls, window: window_, since: '2026-08-22T00:00:00Z' });
  assert.equal(r.verdict, 'UNAIDED');
  assert.equal(r.pr.number, 300);
});

test('a lock-file PR created OUTSIDE the window is AIDED — the #199 shape', () => {
  const pulls = [{ number: 199, created_at: '2026-08-15T03:14:38Z', title: 'chore(deps): lock file maintenance', body: MEND, head: { ref: 'refs/pull/199/head' } }];
  const r = classify({ branches: [], pulls, window: window_, since: '2026-08-08T00:00:00Z' });
  assert.equal(r.verdict, 'AIDED', 'outside the window only a dashboard tick can bypass not-scheduled, so this is not proof');
  assert.equal(r.pr.number, 199);
});

test('a merged lock-file PR is still found after its branch is deleted', () => {
  // Every merged PR here reports head.ref as refs/pull/N/head once the branch is gone — measured on
  // #199. Matching on the branch name ALONE would miss exactly the case we most want to catch.
  const pulls = [{ number: 199, created_at: '2026-08-28T07:10:00Z', title: 'chore(deps): lock file maintenance', body: MEND, head: { ref: 'refs/pull/199/head' } }];
  const r = classify({ branches: [], pulls, window: window_, since: '2026-08-22T00:00:00Z' });
  assert.equal(r.verdict, 'UNAIDED');
});

test('a non-Renovate PR with the same title does NOT count', () => {
  const pulls = [{ number: 400, created_at: '2026-08-28T07:04:00Z', title: 'chore(deps): lock file maintenance', body: 'hand-written, no bot footer', head: { ref: 'refs/pull/400/head' } }];
  const r = classify({ branches: [], pulls, window: window_, since: '2026-08-22T00:00:00Z' });
  assert.equal(r.verdict, 'STILL_STARVED', 'a human reconstructing the PR by hand is precisely what must NOT read as success');
});

test('a PR older than the window under test is ignored', () => {
  const pulls = [{ number: 199, created_at: '2026-08-15T07:04:00Z', title: 'chore(deps): lock file maintenance', body: MEND, head: { ref: 'renovate/lock-file-maintenance' } }];
  const r = classify({ branches: [], pulls, window: window_, since: '2026-08-22T00:00:00Z' });
  assert.equal(r.verdict, 'STILL_STARVED', 'last fortnight\'s PR must not certify this week');
});

test('an UNAIDED result outranks an AIDED one in the same period', () => {
  const pulls = [
    { number: 199, created_at: '2026-08-26T03:14:00Z', title: 'chore(deps): lock file maintenance', body: MEND, head: { ref: 'renovate/lock-file-maintenance' } },
    { number: 300, created_at: '2026-08-28T07:04:00Z', title: 'chore(deps): lock file maintenance', body: MEND, head: { ref: 'renovate/lock-file-maintenance' } },
  ];
  const r = classify({ branches: [], pulls, window: window_, since: '2026-08-22T00:00:00Z' });
  assert.equal(r.verdict, 'UNAIDED');
  assert.equal(r.pr.number, 300);
});
