#!/usr/bin/env node
/**
 * Feature 023 (T009) — write the CI environment files the dev stack needs, from CI secrets.
 *
 * `gen-dev-secrets.mjs` mints the per-stack `stacks/*.env` (the `${VAR:?}` interpolation source for
 * compose). This script writes the THREE remaining files that are gitignored on a dev box and were
 * the original android-e2e "BLOCKED (ci-provisioning)" gap (research R5), filling their secret-bearing
 * keys from the environment (Forgejo Actions secrets) — never a committed literal:
 *
 *   1. infrastructure-as-code/docker/keycloak/secrets/keycloak_db_password.txt   ← KC_DB_PASSWORD
 *   2. infrastructure-as-code/docker/keycloak/.env.local  (KC_DB_PASSWORD=…)     ← KC_DB_PASSWORD
 *      (postgres reads the txt secret; Keycloak reads .env.local — the two MUST match.)
 *   3. frontend/mcm-app/.env.docker  (read by mcm-bff-service-nonsecure)         ← the BFF secrets
 *
 * The non-secret values below are Docker-internal service DNS + dev timeouts (already committed in
 * the compose files + .env.docker.example) — not credentials and not public-host topology. Only the
 * secret-bearing keys come from the environment; an unset required secret ABORTS with no fallback
 * literal (constitution §Secrets Management; the no-inline-secret rule applies to scripts too).
 *
 * The BFF client secrets here MUST equal the throwaway secrets embedded in ci-realm.json (T008) so
 * the imported realm and this .env.docker agree — both are seeded from the same Forgejo CI secrets.
 *
 * Usage (CI step): KC_DB_PASSWORD=… KEYCLOAK_CLIENT_SECRET=… … node scripts/gen-ci-env.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const KC_DIR = resolve(REPO_ROOT, 'infrastructure-as-code/docker/keycloak');

/** Read a required secret from env; abort (no fallback literal) if unset. */
function reqSecret(name) {
  const v = process.env[name];
  if (v == null || v === '') {
    console.error(`[gen-ci-env] required secret ${name} is unset — refusing to write a fallback literal.`);
    process.exit(2);
  }
  return v;
}

const KC_DB_PASSWORD = reqSecret('KC_DB_PASSWORD');
const KEYCLOAK_CLIENT_SECRET = reqSecret('KEYCLOAK_CLIENT_SECRET');
const KEYCLOAK_SERVICE_CLIENT_SECRET = reqSecret('KEYCLOAK_SERVICE_CLIENT_SECRET');
const COOKIE_SECRET = reqSecret('COOKIE_SECRET');
const AGENT_SUBJECT_TOKEN_CLIENT_SECRET = reqSecret('AGENT_SUBJECT_TOKEN_CLIENT_SECRET');
const AGENT_CONFIG_ENC_KEY = reqSecret('AGENT_CONFIG_ENC_KEY');

// 1 + 2 — Keycloak DB password (postgres secret file + Keycloak .env.local; must match each other).
mkdirSync(resolve(KC_DIR, 'secrets'), { recursive: true });
writeFileSync(resolve(KC_DIR, 'secrets/keycloak_db_password.txt'), `${KC_DB_PASSWORD}\n`, 'utf8');
writeFileSync(resolve(KC_DIR, '.env.local'), `KC_DB_PASSWORD=${KC_DB_PASSWORD}\n`, 'utf8');

// 3 — BFF .env.docker. Non-secret values are Docker-internal service DNS (matches the committed
//     .env.docker.example + compose); E2E raises the per-user cost/rate ceilings so a shared test
//     user is not locked out (CLAUDE.md / SC-011). Secrets are injected from env.
const envDocker = `# GENERATED by scripts/gen-ci-env.mjs for CI — DO NOT COMMIT (gitignored).
# Docker-internal hostnames; secret values injected from Forgejo Actions secrets.
KEYCLOAK_URL=http://keycloak-service:8080
KEYCLOAK_PUBLIC_URL=http://localhost:8099
KEYCLOAK_REALM=grumpyrobot
KEYCLOAK_CLIENT_ID=movie-collection-manager
KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}

# BFF service account
KEYCLOAK_SERVICE_CLIENT_ID=mcm-bff-service
KEYCLOAK_SERVICE_CLIENT_SECRET=${KEYCLOAK_SERVICE_CLIENT_SECRET}

# Redis (internal Docker network)
REDIS_URL=redis://mcm-bff-cache-redis:6379

# Cookie signing secret
COOKIE_SECRET=${COOKIE_SECRET}

# Session config (milliseconds)
SESSION_IDLE_TIMEOUT_MS=1800000
SESSION_ABSOLUTE_TIMEOUT_MS=86400000
MAX_CONCURRENT_SESSIONS=10

# mc-service (internal Docker network)
MC_SERVICE_URL=http://mc-service:3001

# Agent Gateway (feature 012 — internal Docker network, --profile agents)
AGENT_GATEWAY_URL=http://movie-assistant-gateway:8000

# Agent subject-token client (feature 012 — RFC 8693 token exchange)
AGENT_SUBJECT_TOKEN_CLIENT_ID=agent-subject-token
AGENT_SUBJECT_TOKEN_CLIENT_SECRET=${AGENT_SUBJECT_TOKEN_CLIENT_SECRET}
AGENT_SUBJECT_TOKEN_AUDIENCE=agent-gateway

# E2E: raise cost/rate ceilings so a shared test user is not locked out across many agent turns.
AGENT_SESSION_COST_CEILING_USD=1000
AGENT_RATE_LIMIT_REQUESTS=10000

# Feature 018 — per-user agent config (BFF→Mongo AES-256-GCM store)
AGENT_CONFIG_ENC_KEY=${AGENT_CONFIG_ENC_KEY}
MONGO_URL=mongodb://mcm-bff-store-mongo:27017
`;
writeFileSync(resolve(REPO_ROOT, 'frontend/mcm-app/.env.docker'), envDocker, 'utf8');

// 4 — web-api-mcp/.env.local. agent-stack.mjs runs the container with `--env-file` this path, so it
// must exist. The TMDB key is normally supplied PER-REQUEST from the per-user agent config (feature
// 018), so a global key is optional (dev leaves it empty); pass TMDB_API_KEY to give the agent flows
// a working key. Outbound-only; never committed.
writeFileSync(
  resolve(REPO_ROOT, 'mcp-servers/web-api-mcp/.env.local'),
  `TMDB_API_KEY=${process.env.TMDB_API_KEY ?? ''}\nTMDB_BASE_URL=https://api.themoviedb.org/3\n`,
  'utf8',
);

console.log(
  '[gen-ci-env] wrote keycloak/secrets/keycloak_db_password.txt, keycloak/.env.local, ' +
    'frontend/mcm-app/.env.docker (secrets from env).',
);
