name: localdev-auth

services:
  keycloak-db:
    image: postgres:18.3-alpine3.23
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql #Environment variable PGDATA changed to version specific (/var/lib/postgresql/18/docker) so volume also changed from /var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/keycloak-db-passwd  # Reference the password from the Docker secret.
      POSTGRES_DB: keycloak
    networks:
      - keycloak-network
    secrets:
      - keycloak-db-passwd
    healthcheck:  # Local health check from within the container in local development.
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  keycloak-service:
    depends_on:
      keycloak-db:
        condition: service_healthy
    image: quay.io/keycloak/keycloak:26.5.5
    restart: unless-stopped
    ports:
      - "127.0.0.1:8099:8080"  # Expose the application port externally on 8099 and restricted to host machine (127.0.0.1).
      #- "127.0.0.1:9000:9000"  # Expose the management port externally for health checks in higher environments, but not in local development.
    env_file:
      - .env.local # Explicitly specify the custom environment file.
    environment:
      KC_HOSTNAME: http://localhost:8099  # Keycloak hostname must be set with external port.
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ***REMOVED***  # Make sure to change password on first login.
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      #KC_DB_PASSWORD:  # Keycloak doesn't support _FILE secrets, so .env.local is used for the database password. Password for keycloak database must be same across .env.local file and what is set inside the keycloak_db_password.txt file.
    command:
      - start-dev  # Use the development mode for faster startup and auto-reload on configuration changes. Not recommended for production use.
    networks:
      - keycloak-network
      - backend-network
    healthcheck:  # Local health check from within the container in local development.  Container image doesn't support curl or wget, so open network connection send HTTP HEAD request and check for successful "HTTP/1.0 200" response.
      test: ["CMD-SHELL", "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  keycloak-mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025" 
      - "1025:1025"
    volumes:
      - keycloak-mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATABASE: /data/mailpit.db
    networks:
      - keycloak-network

networks:
  keycloak-network:  # Allows keycloak-db and keycloak-service to communicate with each other internally within this compose file.
  backend-network:  # Allows external services on this network (e.g. backend API) to connect to Keycloak by referencing the service name keycloak-service:8080.
    external: true  # Assumes the network is already created outside of this compose file.  

volumes:
  keycloak-db-data:
  keycloak-mailpit-data:

secrets:
  keycloak-db-passwd:
    file: ./secrets/keycloak_db_password.txt  # Path to the keycloak database password file on your host. Password for keycloak database must be same across this file and what is set inside the .env.local file.